Vfd 144 esco luokittelun kaytto jif productizerissa
Virtual-Finland-Development/JobsInFinland.Api.Productizer pull request #10
Opened 2022-12-16 06:56 UTC by lassipatanen

2022-12-16 08:37 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Models/Request/JobsRequest.cs
>  public class JobsRequest
Luokan voisi nimetä JobPostingRequest ja siirtää Models/Data/Testbed alle

2022-12-16 08:37 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Services/OccupationCodeMapper.cs
> +public class OccupationCodeMapper : IOccupationCodeMapper
Nämä code mapper luokat ovat käytännössä samanlaisia, eli ne voisi refaktoroida yhdeksi luokaksi ja mudostaa sitten koodissa esim. factory metodilla oikeanlaiseksi.

2022-12-16 08:37 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Services/Codeset/OccupationCodesetService.cs
> +            var codeJsonObject = JsonSerializer.Deserialize<List<OccupationCodeset>>(stream);
Tässä nyt luetaan ammatit tiedostosta, mutta voiko productizerit hakea tämän tiedon Users API:lta?

2022-12-16 09:29 UTC, lsipii requested changes

2022-12-16 09:29 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Client/JobsInFinlandApiClient.cs
> +        var cityNames = _municipalityCodeMapper.GetNamesFromCodes(jobsRequest.Location.Municipalities);
Tässä varmaan olisi saada aikaiseksi joku validaatiovirhe, httpsattus 422, jos inputista tulee municipalities listassa arvoja mutta arvot eivät mappaudu kaupungeiksi -> vähentää ihmettelyä jos devaaja yrittää vääränlaisilla arvoilla tehdä kyselyjä.

2022-12-16 09:29 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Client/JobsInFinlandApiClient.cs
> +        var occupationNames = _occupationCodeMapper.GetNamesFromCodes(jobsRequest.Requirements.Occupations);
Tässä sama validaatio vääränlaisten input-arvojen varalle, nice-to-have nämä molemmat.

2022-12-16 09:29 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Services/Codeset/OccupationCodesetService.cs
> +                _codes.TryAdd(o.Notation, o.PrefLabel.En);
Tähän liittyen pitäisi tehdä valinta että mitä fieldiä käyttää occupations/skills-listoissa inputin arvona. Tuonne data-definitioniin sujahti vaatimus että arvot olisivat niitä urleja:

https://github.com/Virtual-Finland/definitions/pull/27/files#diff-395003ae1e7758294fb4ba6e0ddf3f8af6887887c3ee82ab5fdbae1d0566c45e

Eli määrittelyn mukaan pitäisi tehdä vertailu urlin perusteella eikä notation-koodin. Toki tämä voidaan muuttaa jos se toimii esim. fronttiappiksen kanssa paremmin se notaatio inputtina.

2022-12-16 09:29 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Services/Codeset/OccupationCodesetService.cs
> +            var codeJsonObject = JsonSerializer.Deserialize<List<OccupationCodeset>>(stream);
Kuulostaa melkein että olisi kiva siirtää tämän kaltaiset koodistot ja resurssit johonkin uuteen omaan palveluunsa, kun ei ne ihan kuulosta kuuluvan users-api:n toimintoihinkaan vaikka siellä tällä hetkellä totetutettu.

2022-12-16 09:34 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Services/Codeset/OccupationCodesetService.cs
> +                _codes.TryAdd(o.Notation, o.PrefLabel.En);
TMT-rajapinnan vastauksissa ei itseasiassa näyttäisi tulevan noita notation-koodeja mutta siellä on URL-tunnisteet: jos päädytään muuttamaan data-definitionin notaatioiksi niin sinne tmt:n puolelle tarvitsee rakentaa kanssa vähän hassusti mapperi joka muuttaa notationin vastaavaksi urliksi.

2022-12-16 11:11 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Services/Codeset/OccupationCodesetService.cs
> +                _codes.TryAdd(o.Notation, o.PrefLabel.En);
Ok, muutan tämän niin että käytetään noita URL:ja notaation sijasta.

2022-12-19 17:30 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Program.cs
> +            return Results.ValidationProblem(errors: validationResult.ToDictionary(), statusCode: 422);
Näinköhän tämä response tulee testbedin läpi, kun siellä dokumentaatiossa näyttäisi olevan response muotoa:

`{
  "detail": [
    {
      "loc": [
        "string"
      ],
      "msg": "string",
      "type": "string"
    }
  ]
}`

2022-12-19 17:32 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Models/Request/JobsRequest.cs
>  public class JobsRequest
✅

2022-12-19 17:32 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Services/OccupationCodeMapper.cs
> +public class OccupationCodeMapper : IOccupationCodeMapper
En nyt tuosta uudsta toteutuksesta tiedä oliko se paras mahdollinen, mutta onphana vähemmän duplikoitua koodia.

✅

2022-12-19 17:34 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Client/JobsInFinlandApiClient.cs
> +        var cityNames = _municipalityCodeMapper.GetNamesFromCodes(jobsRequest.Location.Municipalities);
Lisäsin FluentValidation nugetin mukaan projektiin, ja tuossa validoinnissa katsotaan nuo listat läpi.

2022-12-19 17:34 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Client/JobsInFinlandApiClient.cs
> +        var occupationNames = _occupationCodeMapper.GetNamesFromCodes(jobsRequest.Requirements.Occupations);
Kuten yllä

✅

2022-12-19 17:34 UTC, lassipatanen commented on src/JobsInFinland.Api.Productizer/Services/Codeset/OccupationCodesetService.cs
> +                _codes.TryAdd(o.Notation, o.PrefLabel.En);
✅

2022-12-20 08:56 UTC, lsipii approved these changes

2022-12-20 08:56 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Services/OccupationCodeMapper.cs
> +public class OccupationCodeMapper : IOccupationCodeMapper
Jeps, voisihan noista vielä tehdä geneerisiä luokkia noista factory-seteistä vaan ehkä kannattaa mennä feature-edellä ja refaktoroinnit/siistimiset mahdollisesti eri setissä.

2022-12-20 08:56 UTC, lsipii commented on src/JobsInFinland.Api.Productizer/Program.cs
> +            return Results.ValidationProblem(errors: validationResult.ToDictionary(), statusCode: 422);
Tämän pitäisi olla ihan OK, mutta vanhasta toteutuksesta (alempana: https://github.com/Virtual-Finland-Development/JobsInFinland.Api.Productizer/blob/VFD-144-esco-luokittelun-kaytto-jif-productizerissa/src/JobsInFinland.Api.Productizer/Program.cs#L85) voisi korjata että virhetilanteessa palautetaan response bodyssä vastaava problem-virhe tyyliin:

```
return Results.Problem(e.ToString(), statusCode: statusCode);
```

2022-12-20 08:57 UTC, LauriGofore approved these changes

2022-12-20 10:38 UTC, merged